#!/bin/bash
set -e
set -a
. ./site.config
set +a

SYSTEMD_PATH=~/.config/systemd/user
SYSTEMD_FILE=${SITE_NAME}.service
SYSTEMD_FILEPATH=${SYSTEMD_PATH}/${SYSTEMD_FILE}
CADDY_PATH=/etc/caddy/sites-enabled
CADDY_FILE=${SITE_NAME}.site
CADDY_FILEPATH=${CADDY_PATH}/${CADDY_FILE}
SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

pod_start() {
    podman run \
        --name ${SITE_NAME} \
        --rm --replace --detach \
        --env-file ${SCRIPT_DIR}/.env \
        --publish ${HOST_PORT}:${CONTAINER_PORT} \
        --volume ${SCRIPT_DIR}/data:${CONTAINER_DATADIR} \
        ${CONTAINER_IMAGE}
    podman ps | grep ${SITE_NAME}
}

service_generate() {
    podman generate systemd \
        --files --new --name \
        --restart-policy=always \
        --container-prefix="" --separator="" \
        ${SITE_NAME}
    ls *.service
}

service_install() {
    if [ -f "${SYSTEMD_PATH}/${SYSTEMD_FILE}" ]; then
    	echo "Error: already installed in ${SYSTEMD_PATH}/${SYSTEMD_FILE}"
	exit 1
    else
        if [ ! -f "${SCRIPT_DIR}/${SYSTEMD_FILE}" ]; then
            echo "Error: no unit file found. Run 'service generate' to create one."
            exit 1
        else
            mv "${SCRIPT_DIR}/${SYSTEMD_FILE}" "${SYSTEMD_PATH}/"
            systemctl --user daemon-reload
            systemctl --user start ${SITE_NAME}
            systemctl --user enable ${SITE_NAME}
            systemctl --user status ${SITE_NAME} | grep Active
	fi
    fi
}

service_remove() {
    systemctl --user disable ${SITE_NAME}
    systemctl --user stop ${SITE_NAME}
    if [ -f "${SYSTEMD_PATH}/${SYSTEMD_FILE}" ]; then
        mv "${SYSTEMD_PATH}/${SYSTEMD_FILE}" "${SCRIPT_DIR}"
        systemctl --user daemon-reload
    else
        echo "nothing to remove"
        ls "${SYSTEMD_PATH}"
    fi
}

service_status() {
    systemctl --user list-units --type=service | grep ${SITE_NAME}
    systemctl --user status ${SITE_NAME} | grep Active
}

site_generate() {
    local template="$CADDYFILE_TEMPLATE"
    eval "echo \"${template}\"" > "${SCRIPT_DIR}/${CADDY_FILE}"
    echo "writing to file ${SCRIPT_DIR}/${CADDY_FILE}:"
    # cat "${SCRIPT_DIR}/${CADDY_FILE}"
}

site_enable() {
    if [ ! -f "${SCRIPT_DIR}/${CADDY_FILE}" ]; then
        echo "generating Caddy file"
        site_generate
    fi
    sudo mv "${SCRIPT_DIR}/${CADDY_FILE}" "${CADDY_PATH}/${CADDY_FILE}"
    sudo systemctl reload caddy
    # cat "${CADDY_PATH}/${CADDY_FILE}"
    sudo ls -l ${CADDY_PATH}
    echo "site enabled: https://${SITE_URLS}"
}

site_disable() {
    if [ -f "${CADDY_PATH}/${CADDY_FILE}" ]; then
        if [ -f "${SCRIPT_DIR}/${CADDY_FILE}" ]; then
            echo "Error: conflicting file in ${SCRIPT_DIR}"
            exit 1
	fi
        sudo mv "${CADDY_PATH}/${CADDY_FILE}" "${SCRIPT_DIR}/"
        sudo systemctl reload caddy
    else
        echo "Error: site not installed"
	sudo ls ${CADDY_PATH}
    fi
    site_info
}

site_status() {
    ls ${CADDY_PATH}
    curl ${SITE_URLS}
}

auto_install() {
    echo "starting pod"
    pod_start
    echo "generating service file"
    service_generate
    echo "stopping pod"
    podman rm -f "${SITE_NAME}"
    echo "installing service"
    service_install
    echo "generating site file"
    site_generate
    echo "enabling site"
    site_enable
    echo "checking service status"
    cat ${SYSTEMD_PATH}/${SYSTEMD_FILE}
    systemctl --user status ${SITE_NAME}
    echo "checking site status"
    curl https://${SITE_URLS}
}

auto_remove() {
    site_disable
    service_remove
}

case "$1" in
pod)
    if   [ "$2" = "start" ];    then pod_start
    elif [ "$2" = "stop" ];     then podman kill ${SITE_NAME}
    elif [ "$2" = "log" ];      then podman logs -f ${SITE_NAME}
    else
        echo "Error: sub-command unknown"
	exit 1
    fi
    ;;
site)
    if   [ "$2" = "enable" ];   then site_enable
    elif [ "$2" = "install" ];  then site_enable
    elif [ "$2" = "disable" ];  then site_disable
    elif [ "$2" = "remove" ];   then site_disable
    elif [ "$2" = "generate" ]; then site_generate
    elif [ "$2" = "status" ];	then site_status
    else
        echo "Error: sub-command unknown"
	exit 1
    fi
    ;;
service)
    if   [ "$2" = "generate" ]; then service_generate
    elif [ "$2" = "install" ];  then service_install
    elif [ "$2" = "remove" ];   then service_remove
    elif [ "$2" = "enable" ];   then systemctl --user enable ${SITE_NAME}
    elif [ "$2" = "disable" ];  then systemctl --user disable ${SITE_NAME}
    elif [ "$2" = "start" ];    then systemctl --user start ${SITE_NAME}
    elif [ "$2" = "stop" ];     then systemctl --user stop ${SITE_NAME}
    elif [ "$2" = "status" ];   then service_status
    else
        echo "Error: sub-command unknown"
	exit 1
    fi
    ;;
install)
    auto_install
    ;;
remove)
    auto_remove
    ;;
*)
    echo "Error: command not found" >&2
    exit 1
    ;;
esac

